### ISSUE TITLE
Fix javadocs to work with java8

### ISSUE THREAD

**Issue by cmungall** [sba1/ontologizer#4]
java8 is stricter when it comes to javadocs. Trying to build @drseb's branch with mvn:

```
ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.3:jar (generate-javadoc-jar) on project ontologizer: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - /Users/cjm/repos/drseb/ontologizer/ontologizer/src/ontologizer/AbstractStudySetResult.java:40: warning: no description for @param
[ERROR] * @param goTermID
```

This seems to be one possible workaround:
http://www.locked.de/2015/04/05/how-to-ignore-maven-javadoc-errors-in-java-8/

But doesn't seem to work for me

**Comment by sba1** [comment]
PR #3 deals with the problem, but not 100% satisfactory. Temporary solution that might work: Add `-Dmaven.javadoc.skip=true` to the mvn command (works only if you don't need Javadoc). But yes, the proper solution is to fix Javadocs. Contributions are welcome :)

**Comment by sba1** [comment]
I fixed all errors, there are still warnings but the build passes according to Travis. Thanks for the report.
