### ISSUE TITLE
mvn package failing 

### ISSUE THREAD

**Issue by johntiger1** [sba1/ontologizer#6]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] ontologizer.parent ................................. SUCCESS [  0.007 s]
[INFO] ontologizer ........................................ SUCCESS [01:05 min]
[INFO] ontologizer.dataprep ............................... SUCCESS [ 19.301 s]
[INFO] ontologizer.obogen ................................. SUCCESS [  0.325 s]
[INFO] ontologizer.jmh .................................... SUCCESS [ 15.836 s]
[INFO] ontologizer.changelog .............................. SUCCESS [  0.247 s]
[INFO] ontologizer.grappa ................................. SUCCESS [  1.301 s]
[INFO] ontologizer.svd .................................... SUCCESS [  0.555 s]
[INFO] ontologizer.benchmark .............................. SUCCESS [  1.809 s]
[INFO] ontologizer.tests .................................. SUCCESS [ 18.764 s]
[INFO] ontologizer.gui .................................... SUCCESS [ 45.634 s]
[INFO] ontologizer.cmdline ................................ FAILURE [  0.449 s]
[INFO] ontologizer.cmdline.printopts ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:49 min
[INFO] Finished at: 2017-07-28T17:24:31-04:00
[INFO] Final Memory: 59M/447M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (default) on project ontologizer.cmdline: Command execution failed.: Cannot run program "pandoc" (in directory "C:\Users\johnp\Desktop\git_stuff\seb_onto\ontologizer\ontologizer.cmdline\doc"): CreateProcess error=2, The system cannot find the file specified -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ontologizer.cmdline

**Comment by sba1** [comment]
You need to install pandoc for the maven build.

**Comment by johntiger1** [comment]
Thanks that + restart fixed it
