### ISSUE TITLE
[question] Slim View

### ISSUE THREAD

**Issue by johntiger1** [sba1/ontologizer#9]
Sorry for the simple question, but I want to confirm, what is a "slim view" of a graph? Is it just the regular DirectedGraph, except using smaller primitives for faster performance?

**Comment by sba1** [comment]
> Sorry for the simple question, but I want to confirm, what is a "slim
> view" of a graph? Is it just the regular DirectedGraph, except using
> smaller primitives for faster performance?

Yes, you are right.

**Comment by johntiger1** [comment]
Thanks
